# Generated by Django 4.1.7 on 2023-05-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("items", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.product"
            ),
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
