# Generated by Django 5.0.2 on 2024-02-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
