# Generated by Django 5.0.2 on 2024-04-21 01:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_product_amount'),
        ('reviews', '0003_review_views'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product')},
        ),
        migrations.RemoveField(
            model_name='review',
            name='views',
        ),
    ]
